import { formatDateTime } from '../../utils/formatters';
import DetailGrid from '../ui/DetailGrid';
import AiResultPanel, { AiMeta, AiSection, UncertainBanner } from './AiResultPanel';
import Alert from '../ui/Alert';

// Displays the AI Evidence Analysis Agent's most recent result for a single
// evidence item and lets an officer/inspector (re-)run it on demand.
// Everything here is clearly framed as AI-generated and advisory - it never
// represents a confirmed finding, and running it never changes the evidence
// file or complaint/inspection.
function EvidenceAnalysisPanel({ evidenceItem, analysis, isRunning, error, onRun }) {
  return (
    <AiResultPanel
      as="div"
      titleAs="h3"
      title="AI Evidence Analysis (Advisory)"
      hasResult={Boolean(analysis)}
      isRunning={isRunning}
      error={error}
      status={analysis?.status}
      failureMessage={`The last AI analysis attempt failed: ${analysis?.error_message || 'Unknown error.'}`}
      emptyMessage={`No AI analysis yet for ${evidenceItem?.file_name || 'this item'}. Analyzing extracts visible text, product details, and observations for your review - it never changes the evidence file.`}
      onRun={onRun}
      runLabel="Analyze with AI"
      rerunLabel="Re-analyze"
      runningLabel="Analyzing…"
    >
      {analysis?.is_uncertain && (
        <UncertainBanner>
          AI confidence is low or some details were hard to read. Treat this analysis with caution and review the
          evidence yourself.
        </UncertainBanner>
      )}

      {analysis?.possible_expired === true && (
        <Alert tone="warning">
          Possible expired product based on visible date &mdash; for officer/inspector review only. This is not a
          confirmed finding.
        </Alert>
      )}

      {analysis?.extracted_text && (
        <AiSection title="Extracted text (OCR)">
          <p className="whitespace-pre-wrap rounded-md bg-white p-2 text-sm">{analysis.extracted_text}</p>
        </AiSection>
      )}

      {analysis &&
        (analysis.product_name ||
          analysis.manufacturer ||
          analysis.batch_lot_number ||
          analysis.manufacturing_date_text ||
          analysis.expiry_date_text) && (
          <DetailGrid>
            {analysis.product_name && (
              <>
                <dt>Product</dt>
                <dd>{analysis.product_name}</dd>
              </>
            )}
            {analysis.manufacturer && (
              <>
                <dt>Manufacturer</dt>
                <dd>{analysis.manufacturer}</dd>
              </>
            )}
            {analysis.batch_lot_number && (
              <>
                <dt>Batch / lot</dt>
                <dd>{analysis.batch_lot_number}</dd>
              </>
            )}
            {analysis.manufacturing_date_text && (
              <>
                <dt>Manufacturing date (as printed)</dt>
                <dd>{analysis.manufacturing_date_text}</dd>
              </>
            )}
            {analysis.expiry_date_text && (
              <>
                <dt>Expiry / best-before (as printed)</dt>
                <dd>{analysis.expiry_date_text}</dd>
              </>
            )}
          </DetailGrid>
        )}

      {analysis?.packaging_observations && (
        <AiSection title="Packaging / label observations">
          <p>{analysis.packaging_observations}</p>
        </AiSection>
      )}

      {analysis?.hygiene_observations && (
        <AiSection title="Hygiene / food condition observations">
          <p>{analysis.hygiene_observations}</p>
        </AiSection>
      )}

      {analysis?.foreign_object_observations && (
        <AiSection title="Possible foreign object observations">
          <p>{analysis.foreign_object_observations}</p>
        </AiSection>
      )}

      {analysis && (
        <AiMeta>
          Generated by {analysis.model_used} on {formatDateTime(analysis.created_at)} &middot; confidence{' '}
          {analysis.confidence !== null && analysis.confidence !== undefined
            ? `${Math.round(analysis.confidence * 100)}%`
            : 'unknown'}
          . This is an AI observation only, not a confirmed finding.
        </AiMeta>
      )}
    </AiResultPanel>
  );
}

export default EvidenceAnalysisPanel;
