"""LiveKit Agent worker for the Inspector Assistant voice channel.

Standalone process, run separately from the FastAPI app (its own pm2
process). Connects to LiveKit Cloud, gets dispatched into whichever room a
browser joins via app.services.assistant_service.create_livekit_session_for_conversation,
and pipes the inspector's speech through STT -> the existing Inspector
Assistant RAG pipeline (over HTTP, POST /api/v1/voice/turn on the FastAPI
backend) -> TTS. Holds no direct database access and no RAG logic of its
own - this is purely the voice I/O layer (docs/AI_AGENTS_ARCHITECTURE.md).

The llm_node() override below fully replaces LLM generation with a call to
our own backend, following LiveKit's documented "Replacing LLM output"
pattern (https://docs.livekit.io/recipes/replacing_llm_output/) - the
AgentSession still needs an `llm=` instance passed to it to construct
correctly, but it is never actually invoked since llm_node never calls
self.session.llm.chat(...).

on_user_turn_completed() no longer speaks its filler unconditionally - after
the backend's answer stage went Groq-primary, most turns finish in 2-8s, and
a filler on every single turn (including "thank you") felt sluggish and
robotic rather than helpful. Instead it schedules the filler on a delay
(FILLER_DELAY_SECONDS) and llm_node cancels that pending task the moment the
real answer starts arriving - so the filler only ever plays when the backend
is genuinely slow enough to need it.

STREAMING (this revision): /api/v1/voice/turn now returns the answer as
Server-Sent Events (app/api/voice/router.py) instead of one JSON blob -
llm_node reads it as a stream and yields each text delta to the TTS
pipeline as it arrives, rather than waiting for the whole answer. This is
the actual latency win: TTS starts speaking the first words of the answer
while the rest is still being generated by Groq, instead of waiting for the
full response like before. The filler task is now cancelled as soon as the
connection opens and the first byte comes back, not after the full answer.

_http_client is now a single module-scope httpx.AsyncClient reused across
every turn, instead of creating a new client (new TCP+TLS handshake) inside
llm_node on every single question.

FIX (earlier revision, still in effect): ctx.connect() runs BEFORE
session.start(). Doing it in the previous order (start, then connect)
handed AgentSession a room object that hadn't joined LiveKit yet - it could
silently fail to bind audio tracks on some dispatches and not others, which
was the most likely explanation for "works sometimes, not others" with no
error in the logs.
"""

import asyncio
import json
import logging
import os

import httpx
from dotenv import load_dotenv
from livekit.agents import Agent, AgentServer, AgentSession, JobContext, JobProcess, cli, inference
from livekit.plugins import silero

load_dotenv(".env.local")

logger = logging.getLogger("inspector-voice-worker")
logger.setLevel(logging.INFO)

BACKEND_BASE_URL = os.environ["BACKEND_BASE_URL"]  # e.g. http://localhost:8000, or your EC2 backend URL
VOICE_TURN_PATH = "/api/v1/voice/turn"
HTTP_TIMEOUT_SECONDS = 45.0
AGENT_NAME = os.environ.get("LIVEKIT_AGENT_NAME", "inspector-voice-assistant")
FILLER_DELAY_SECONDS = 2.5

# Reused across every turn and every session this process handles - avoids
# a fresh TCP+TLS handshake to the backend on every single question.
_http_client = httpx.AsyncClient(timeout=HTTP_TIMEOUT_SECONDS)

server = AgentServer()


def prewarm(proc: JobProcess) -> None:
    proc.userdata["vad"] = silero.VAD.load()


server.setup_fnc = prewarm


class InspectorAssistant(Agent):
    def __init__(self, session_token: str) -> None:
        super().__init__(
            instructions=(
                "You are the Inspector Assistant, speaking with a food-safety "
                "inspector in the field. Keep replies short, plain, and speakable - "
                "no markdown, no bullet points, no asterisks."
            )
        )
        self._session_token = session_token
        self._filler_task: asyncio.Task | None = None

    async def on_enter(self) -> None:
        await self.session.say("Hi, I'm the Inspector Assistant. What do you need help with?")

    async def on_user_turn_completed(self, chat_ctx, new_message) -> None:
        # Don't speak immediately - only if the backend hasn't started
        # responding within FILLER_DELAY_SECONDS. llm_node cancels this task
        # as soon as the stream connection opens, so a fast turn never
        # hears the filler.
        async def _delayed_filler() -> None:
            await asyncio.sleep(FILLER_DELAY_SECONDS)
            await self.session.say("Let me check on that.")

        if self._filler_task and not self._filler_task.done():
            self._filler_task.cancel()
        self._filler_task = asyncio.create_task(_delayed_filler())

    async def llm_node(self, chat_ctx, tools, model_settings=None):
        async def process_stream():
            transcript = ""
            for item in reversed(chat_ctx.items):
                if getattr(item, "role", None) == "user":
                    transcript = item.text_content or ""
                    break

            if not transcript:
                if self._filler_task and not self._filler_task.done():
                    self._filler_task.cancel()
                yield "Sorry, I didn't catch that - could you say it again?"
                return

            try:
                async with _http_client.stream(
                    "POST",
                    f"{BACKEND_BASE_URL}{VOICE_TURN_PATH}",
                    json={"transcript": transcript, "session_token": self._session_token},
                ) as response:
                    response.raise_for_status()
                    # Cancel the filler as soon as the stream opens (first
                    # byte back), not after the full answer - this is what
                    # actually shortens the "let me check" window now.
                    if self._filler_task and not self._filler_task.done():
                        self._filler_task.cancel()
                    async for line in response.aiter_lines():
                        if not line.startswith("data: "):
                            continue
                        payload = line[len("data: ") :]
                        if payload == "[DONE]":
                            break
                        yield payload
            except httpx.HTTPError:
                logger.exception("voice-turn request failed")
                if self._filler_task and not self._filler_task.done():
                    self._filler_task.cancel()
                yield "Sorry, I couldn't reach the assistant just now - please try again."
                return

        return process_stream()


@server.rtc_session(agent_name=AGENT_NAME)
async def entrypoint(ctx: JobContext) -> None:
    metadata = json.loads(ctx.job.metadata or "{}")
    session_token = metadata.get("voice_session_token")
    if not session_token:
        logger.error("Voice job dispatched with no voice_session_token in metadata - refusing to start")
        return

    # Join the room FIRST. AgentSession(room=ctx.room) needs the room to
    # already be connected - starting the session before connecting was
    # the source of the earlier intermittent "sometimes it just doesn't
    # respond" behavior.
    await ctx.connect()

    session = AgentSession(
        stt=inference.STT(model="deepgram/nova-3-general"),
        llm=inference.LLM(model="openai/gpt-4.1-mini"),  # never actually called - see class docstring
        tts=inference.TTS(model="cartesia/sonic-3", voice="3b554273-4299-48b9-9aaf-eefd438e3941"),
        vad=ctx.proc.userdata["vad"],
        turn_detection=inference.TurnDetector(),
        min_endpointing_delay=1.0,  # was defaulting to ~0.3-0.5s - too tight for slower/thoughtful speech
        max_endpointing_delay=6.0,  # upper bound so a long pause still eventually commits the turn
    )

    agent = InspectorAssistant(session_token)
    await session.start(agent=agent, room=ctx.room)


if __name__ == "__main__":
    cli.run_app(server)