"""add inspection assignment workflow

Revision ID: 30824dc06f71
Revises: 5867bff9f79e
Create Date: 2026-08-27 14:59:01.550742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30824dc06f71'
down_revision: Union[str, None] = '5867bff9f79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to_staff_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_staff_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('assigned', 'in_progress', 'completed', name='assignment_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_staff_id'], ['staff_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_to_staff_id'], ['staff_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_assigned_to_staff_id'), 'assignments', ['assigned_to_staff_id'], unique=False)
    op.create_index(op.f('ix_assignments_complaint_id'), 'assignments', ['complaint_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('inspector_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_status', sa.Enum('scheduled', 'in_progress', 'completed', name='inspection_status'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_recommended', sa.Text(), nullable=True),
    sa.Column('report_storage_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspector_id'], ['staff_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_complaint_id'), 'inspections', ['complaint_id'], unique=True)
    op.create_index(op.f('ix_inspections_inspector_id'), 'inspections', ['inspector_id'], unique=False)
    op.create_table('inspection_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('check_code', sa.String(length=50), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='finding_severity'), nullable=False),
    sa.Column('compliant', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_findings_inspection_id'), 'inspection_findings', ['inspection_id'], unique=False)
    op.add_column('evidence', sa.Column('inspection_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_evidence_inspection_id'), 'evidence', ['inspection_id'], unique=False)
    op.create_foreign_key(
        'evidence_inspection_id_fkey', 'evidence', 'inspections', ['inspection_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('evidence_inspection_id_fkey', 'evidence', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_inspection_id'), table_name='evidence')
    op.drop_column('evidence', 'inspection_id')
    op.drop_index(op.f('ix_inspection_findings_inspection_id'), table_name='inspection_findings')
    op.drop_table('inspection_findings')
    op.drop_index(op.f('ix_inspections_inspector_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_complaint_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_assignments_complaint_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigned_to_staff_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###

    # Postgres ENUM types are separate objects from the tables that use
    # them - dropping the tables above does not drop these, so they must be
    # dropped explicitly or a re-upgrade after this downgrade fails with
    # "type already exists".
    bind = op.get_bind()
    sa.Enum(name='assignment_status').drop(bind, checkfirst=True)
    sa.Enum(name='inspection_status').drop(bind, checkfirst=True)
    sa.Enum(name='finding_severity').drop(bind, checkfirst=True)
