"""add complaint management tables

Revision ID: 5867bff9f79e
Revises: 0536e568a656
Create Date: 2026-08-27 14:03:23.259679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5867bff9f79e'
down_revision: Union[str, None] = '0536e568a656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_categories_key'), 'complaint_categories', ['key'], unique=True)
    op.create_table('businesses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_business_name'), 'businesses', ['business_name'], unique=False)
    op.create_index(op.f('ix_businesses_district_id'), 'businesses', ['district_id'], unique=False)
    op.create_index(op.f('ix_businesses_license_number'), 'businesses', ['license_number'], unique=False)
    op.create_table('complaint_sequences',
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('last_seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('district_id', 'year')
    )
    op.create_table('complaints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_number', sa.String(length=30), nullable=False),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'needs_information', 'verified', 'rejected', 'duplicate', 'insufficient_evidence', 'assigned', 'inspection_scheduled', 'under_inspection', 'inspection_completed', 'action_in_progress', 'resolved', 'closed', 'cancelled', name='complaint_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='complaint_priority'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('address_line', sa.String(length=500), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['complaint_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_business_id'), 'complaints', ['business_id'], unique=False)
    op.create_index(op.f('ix_complaints_category_id'), 'complaints', ['category_id'], unique=False)
    op.create_index(op.f('ix_complaints_complaint_number'), 'complaints', ['complaint_number'], unique=True)
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_district_id'), 'complaints', ['district_id'], unique=False)
    op.create_index('ix_complaints_district_priority', 'complaints', ['district_id', 'priority'], unique=False)
    op.create_index('ix_complaints_district_status', 'complaints', ['district_id', 'status'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index(op.f('ix_complaints_submitted_by_user_id'), 'complaints', ['submitted_by_user_id'], unique=False)
    op.create_table('complaint_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.Enum('submitted', 'under_review', 'needs_information', 'verified', 'rejected', 'duplicate', 'insufficient_evidence', 'assigned', 'inspection_scheduled', 'under_inspection', 'inspection_completed', 'action_in_progress', 'resolved', 'closed', 'cancelled', name='complaint_status'), nullable=True),
    sa.Column('new_status', sa.Enum('submitted', 'under_review', 'needs_information', 'verified', 'rejected', 'duplicate', 'insufficient_evidence', 'assigned', 'inspection_scheduled', 'under_inspection', 'inspection_completed', 'action_in_progress', 'resolved', 'closed', 'cancelled', name='complaint_status'), nullable=False),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_complaint_status_history_complaint_created', 'complaint_status_history', ['complaint_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_complaint_status_history_complaint_id'), 'complaint_status_history', ['complaint_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('storage_bucket', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_complaint_id'), 'evidence', ['complaint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_complaint_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_complaint_status_history_complaint_id'), table_name='complaint_status_history')
    op.drop_index('ix_complaint_status_history_complaint_created', table_name='complaint_status_history')
    op.drop_table('complaint_status_history')
    op.drop_index(op.f('ix_complaints_submitted_by_user_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index('ix_complaints_district_status', table_name='complaints')
    op.drop_index('ix_complaints_district_priority', table_name='complaints')
    op.drop_index(op.f('ix_complaints_district_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_number'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_business_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_table('complaint_sequences')
    op.drop_index(op.f('ix_businesses_license_number'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_district_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_business_name'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_complaint_categories_key'), table_name='complaint_categories')
    op.drop_table('complaint_categories')
    # ### end Alembic commands ###
