"""Add ComplaintSubcategory and food_type

Revision ID: 78629cdd0f77
Revises: 6c7c65050de6
Create Date: 2026-09-10 11:48:49.168106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.

revision: str = '78629cdd0f77'
down_revision: Union[str, None] = '6c7c65050de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_subcategories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['complaint_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_subcategories_category_id'), 'complaint_subcategories', ['category_id'], unique=False)
    op.add_column('complaints', sa.Column('subcategory_id', sa.Uuid(), nullable=True))
    op.add_column('complaints', sa.Column('food_type', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_complaints_subcategory_id'), 'complaints', ['subcategory_id'], unique=False)
    op.create_foreign_key(None, 'complaints', 'complaint_subcategories', ['subcategory_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_subcategory_id'), table_name='complaints')
    op.drop_column('complaints', 'food_type')
    op.drop_column('complaints', 'subcategory_id')
    op.drop_index(op.f('ix_complaint_subcategories_category_id'), table_name='complaint_subcategories')
    op.drop_table('complaint_subcategories')
    # ### end Alembic commands ###
