"""Add food analyst, samples, legal actions, and clarifications

Revision ID: 9a835e58f305
Revises: 78629cdd0f77
Create Date: 2026-09-10 18:39:11.218544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add food analyst, samples, legal actions, and clarifications

Revision ID: 9a835e58f305
Revises: 78629cdd0f77
Create Date: 2026-09-10 18:39:11.218544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a835e58f305'
down_revision: Union[str, None] = '78629cdd0f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Manual enum extensions ---
    # Postgres requires non-transactional execution for ALTER TYPE ADD VALUE
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'food_analyst'")
    op.execute("ALTER TYPE complaint_status ADD VALUE IF NOT EXISTS 'sample_pending_lab_result'")
    op.execute("ALTER TYPE complaint_status ADD VALUE IF NOT EXISTS 'legal_action_in_progress'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'clarification_requested'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'citizen_responded'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'sample_result_received'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'legal_action_initiated'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_sequences',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('complaint_clarifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('request_history_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by_id', sa.Uuid(), nullable=False),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_history_id'], ['complaint_status_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['staff_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_clarifications_complaint_id'), 'complaint_clarifications', ['complaint_id'], unique=False)
    op.create_table('samples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sample_code', sa.String(length=30), nullable=False),
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('seal_number', sa.String(length=100), nullable=True),
    sa.Column('collected_by_id', sa.Uuid(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('collected', 'dispatched', 'received_at_lab', 'testing_in_progress', 'result_received', name='sample_status'), nullable=False),
    sa.Column('dispatched_to_id', sa.Uuid(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lab_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collected_by_id'], ['staff_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dispatched_to_id'], ['staff_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_inspection_id'), 'samples', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_samples_sample_code'), 'samples', ['sample_code'], unique=True)
    op.create_table('lab_test_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('food_analyst_id', sa.Uuid(), nullable=False),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_storage_path', sa.String(length=500), nullable=True),
    sa.Column('verdict', sa.Enum('safe', 'adulterated', 'unsafe', 'misbranded', 'misleadingly_advertised', name='lab_verdict'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_analyst_id'], ['staff_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id')
    )
    op.create_table('legal_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('lab_test_result_id', sa.Uuid(), nullable=True),
    sa.Column('initiated_by_id', sa.Uuid(), nullable=False),
    sa.Column('fss_act_section', sa.String(length=100), nullable=True),
    sa.Column('action_type', sa.Enum('fine', 'licence_suspension', 'licence_cancellation', 'prosecution_referral', name='legal_action_type'), nullable=False),
    sa.Column('fine_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('case_reference', sa.String(length=200), nullable=True),
    sa.Column('court_or_tribunal', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('initiated', 'in_progress', 'concluded', name='legal_action_status'), nullable=False),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['staff_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lab_test_result_id'], ['lab_test_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_actions_complaint_id'), 'legal_actions', ['complaint_id'], unique=False)
    op.drop_constraint('uq_assignments_complaint_id', 'assignments', type_='unique')
    op.drop_index('ix_assignments_complaint_id', table_name='assignments')
    op.create_index(op.f('ix_assignments_complaint_id'), 'assignments', ['complaint_id'], unique=True)
    op.drop_constraint('uq_refresh_sessions_token_hash', 'refresh_sessions', type_='unique')
    op.alter_column('staff_profiles', 'district_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_profiles', 'district_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('uq_refresh_sessions_token_hash', 'refresh_sessions', ['token_hash'])
    op.create_index('ix_rag_document_chunks_embedding', 'rag_document_chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index('ix_complaints_location', 'complaints', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_complaints_location', 'complaints', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_businesses_location', 'businesses', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_businesses_location', 'businesses', ['location'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_assignments_complaint_id'), table_name='assignments')
    op.create_index('ix_assignments_complaint_id', 'assignments', ['complaint_id'], unique=False)
    op.create_unique_constraint('uq_assignments_complaint_id', 'assignments', ['complaint_id'])
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_legal_actions_complaint_id'), table_name='legal_actions')
    op.drop_table('legal_actions')
    op.drop_table('lab_test_results')
    op.drop_index(op.f('ix_samples_sample_code'), table_name='samples')
    op.drop_index(op.f('ix_samples_inspection_id'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_complaint_clarifications_complaint_id'), table_name='complaint_clarifications')
    op.drop_table('complaint_clarifications')
    op.drop_table('sample_sequences')
    # ### end Alembic commands ###
