"""Add query_type and rag_used to AssistantMessage

Revision ID: a1f19cf2492b
Revises: 9a835e58f305
Create Date: 2026-09-12 20:31:37.054384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f19cf2492b'
down_revision: Union[str, None] = '9a835e58f305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant_messages', sa.Column('query_type', sa.String(length=50), nullable=True))
    op.add_column('assistant_messages', sa.Column('rag_used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant_messages', 'rag_used')
    op.drop_column('assistant_messages', 'query_type')
    # ### end Alembic commands ###
